In [29]:
import pandas as pd
import numpy as np

In [30]:
pwd

'C:\\Morgan Stanley\\quant-challenge\\Data Ordering Notebooks'

In [31]:
akos_df = pd.read_csv('../data/akos.csv')

In [32]:
akos_df

               County Name  Station
0       Saint Louis County    72745
1       Saint Louis County    KDYT0
2       Saint Louis County    KCOQ0
3             Scott County    KFCM0
4             Scott County    KGYL0
..                     ...      ...
77  Yellow Medicine County    KGDB0
78  Yellow Medicine County    KMVE0
79  Yellow Medicine County    KOVL0
80  Yellow Medicine County    KMML0
81  Yellow Medicine County    KCNB0

[82 rows x 2 columns]

In [33]:
saska_df = pd.read_csv('../data/counties_saska.csv')

In [34]:
saska_df

        County Name  Station
0   Marshall County    KCKN0
1   Marshall County    UYB6K
2     Martin County    KFRM0
3     Martin County    KMJQ0
4     Martin County    KJYG0
..              ...      ...
73      Rock County    KOTG0
74    Roseau County    P6529
75    Roseau County    KHCO0
76    Roseau County    KRRT0
77    Roseau County    X9FED

[78 rows x 2 columns]

In [35]:
lori_df = pd.read_csv('../data/Gagyi-Lori-Counties-Statioins.csv')

In [36]:
lori_df

          County Name  Station
0       Aitkin County    KAIT0
1       Aitkin County    KHZX0
2        Anoka County    9NRIJ
3       Becker County    KDTL0
4       Becker County    KPKD0
5     Beltrami County    X9FED
6     Beltrami County    72755
7       Benton County    72655
8    Big Stone County    KVVV0
9   Blue Earth County    KMKT0
10       Brown County    KULM0
11     Carlton County    KCOQ0
12     Carlton County    KMZH0
13      Carver County    KFCM0
14      Carver County    KGYL0
15        Cass County    KY490
16        Cass County    KXVG0
17        Cass County    KPWC0
18        Cass County    KSAZ0
19    Chippewa County    KMVE0
20    Chippewa County    KBDH0
21     Chisago County    KROS0
22        Clay County    KJKJ0
23        Clay County    KDTL0
24  Clearwater County    KFSE0
25  Clearwater County    72755
26        Cook County    KGNA0
27        Cook County    KCKC0
28  Cottonwood County    KMWM0
29   Crow Wing County    KBRD0
30   Crow Wing County    KAIT0
31   Crow Wing County    KPWC0
32      Dakota County    KSYN0
33      Dakota County    KLVN0
34       Dodge County    KTOB0
35     Douglas County    KAXN0
36   Faribault County    KFRM0
37   Faribault County    KAEL0

In [37]:
huni_df = pd.read_csv('../data/Huni_2.csv', sep=';')

In [38]:
huni_df

                 County Name  Station
0            Fillmore County    KFKA0
1            Freeborn County    KAEL0
2             Goodhue County    KSYN0
3               Grant County    KY630
4            Hennepin County    KMIC0
5            Hennepin County    KFCM0
6             Houston County    KONA0
7             Houston County    KFKA0
8             Hubbard County    KPKD0
9              Isanti County    KCBG0
10             Itasca County    KGPZ0
11            Jackson County    KMJQ0
12            Kanabec County    KJMR0
13          Kandiyohi County    KBDH0
14            Kittson County    KHCO0
15        Koochiching County    72747
16      Lac qui Parle County    KDXX0
17               Lake County    KTWM0
18               Lake County    KBFW0
19  Lake of the Woods County    KFGN0
20  Lake of the Woods County    KBDE0
21           Le Sueur County    KMKT0
22           Le Sueur County    KFBL0
23            Lincoln County    KCNB0
24            Lincoln County    KMML0
25            Lincoln County    KPQN0
26               Lyon County    KMML0
27             McLeod County    KGYL0
28             McLeod County    KHCD0
29           Mahnomen County    KFSE0
30           Mahnomen County    KDTL0

In [39]:
df = pd.concat([akos_df, saska_df, lori_df, huni_df], ignore_index=True)

In [40]:
df.to_csv('county-station.csv')

In [41]:
df

            County Name  Station
0    Saint Louis County    72745
1    Saint Louis County    KDYT0
2    Saint Louis County    KCOQ0
3          Scott County    KFCM0
4          Scott County    KGYL0
..                  ...      ...
224         Lyon County    KMML0
225       McLeod County    KGYL0
226       McLeod County    KHCD0
227     Mahnomen County    KFSE0
228     Mahnomen County    KDTL0

[229 rows x 2 columns]